const linksArray = [
  "https://www.gosuslugi.ru/",
  "https://www.sberbank.ru/",
  "https://epp.genproc.gov.ru",
  "https://ach.gov.ru",
  "https://www.scrf.gov.ru",
  "https://mil.ru",
  "https://www.vtb.ru/",
  "https://www.open.ru/",
  "https://sovcombank.ru/",
  "https://www.psbank.ru/",
  "https://abr.ru/",
  "https://lenta.ru/",
  "http://kremlin.ru/",
  "https://www.cbr.ru/",
  "https://www.vesti.ru/",
  "https://www.rt.com/",
  "https://smotrim.ru/",
  "https://vgtrk.ru/",
  "http://council.gov.ru/",
  "http://duma.gov.ru/",
  "https://gossluzhba.gov.ru/",
  "https://zakupki.gov.ru",
];

module.exports = linksArray;
