// const linksArray1 = [
//   "https://vk.com/",
//   "https://www.gosuslugi.ru/",
//   "https://www.sberbank.ru/",
//   "https://epp.genproc.gov.ru",
//   "https://ach.gov.ru",
//   "https://www.scrf.gov.ru",
//   "https://mil.ru",
//   "https://www.vtb.ru/",
//   "https://www.open.ru/",
//   "https://sovcombank.ru/",
//   "https://www.psbank.ru/",
//   "https://abr.ru/",
//   "https://lenta.ru/",
//   "http://kremlin.ru/",
//   "https://www.cbr.ru/",
//   "https://www.vesti.ru/",
//   "https://www.rt.com/",
//   "https://smotrim.ru/",
//   "https://vgtrk.ru/",
//   "http://council.gov.ru/",
//   "http://duma.gov.ru/",
//   "https://gossluzhba.gov.ru/",
//   "https://zakupki.gov.ru",
//   "http://life.ru/",
//   "http://www.rbc.ru/",
//   "https://russian.rt.com/",
//   "http://www.vedomosti.ru/",
//   "https://www.gazeta.ru/",
//   "http://lenta.ru/",
//   "http://www.interfax.ru/",
//   "http://www.kommersant.ru/",
//   "http://www.vesti.ru/",
//   "https://ria.ru/",
//   "https://rg.ru/",
//   "http://izvestia.ru/",
//   "https://tass.ru/",
//   "https://www.rbc.ru/",
//   "https://www.ntv.ru/",
//   "http://defence.council.gov.ru/",
//   "https://360tv.ru/",
//   "https://www.kp.ru/",
//   "https://www.fontanka.ru/",
//   "https://www.mk.ru/",
//   "https://news.ru/",
//   "https://www.investing.com/",
//   "https://sputniknews.com",
//   "https://yandex.ru",
//   "https://eadaily.com/",
//   "http://alania.gov.ru/",
//   "http://archives.gov.ru/",
//   "http://budget.gov.ru/",
//   "http://council.gov.ru/",
//   "http://duma.gov.ru/",
//   "http://edu.rs.gov.ru/",
//   "http://fssp.gov.ru/",
//   "http://fstec.ru/",
//   "http://lenino.rk.gov.ru/",
//   "http://mil.ru/",
//   "http://minobr.saratov.gov.ru/",
//   "http://obrnadzor.gov.ru/",
//   "http://pravo.gov.ru/",
//   "http://publication.pravo.gov.ru/",
//   "http://rospn.gov.ru/",
//   "http://science.gov.ru/",
//   "http://sfo.gov.ru/",
//   "http://skfo.gov.ru/",
//   "http://svr.gov.ru/",
//   "http://szfo.gov.ru/",
//   "http://tatishevo.saratov.gov.ru/",
//   "http://udprf.ru/",
//   "http://uralfo.gov.ru/",
//   "http://www-fsb.com/",
//   "http://www.chechnya.gov.ru/",
//   "http://www.fedsfm.ru/",
//   "http://www.fsb.gov.ru/",
//   "http://www.fso.gov.ru/",
//   "http://www.fsvts.gov.ru/",
//   "http://www.government.gov.ru/",
//   "http://www.gusp.gov.ru/",
//   "http://www.scrf.gov.ru/",
//   "http://www.svr.gov.ru/",
//   "https://01.mchs.gov.ru/",
//   "https://08.mchs.gov.ru/",
//   "https://15.mchs.gov.ru/",
//   "https://18.mchs.gov.ru/",
//   "https://23.mchs.gov.ru/",
//   "https://32.mchs.gov.ru/",
//   "https://43.mchs.gov.ru/",
//   "https://45.mchs.gov.ru/",
//   "https://48.mchs.gov.ru/",
//   "https://53.mchs.gov.ru/",
//   "https://61.mchs.gov.ru/",
//   "https://74.mchs.gov.ru/",
//   "https://78.mchs.gov.ru/",
//   "https://87.mchs.gov.ru/",
//   "https://ach.gov.ru/",
//   "https://birobidzhan.roskazna.gov.ru/",
//   "https://bus.gov.ru/",
//   "https://culture.gov.ru/",
//   "https://customs.gov.ru/",
//   "https://digital.ac.gov.ru/",
//   "https://digital.gov.ru/",
//   "https://edu.gov.ru/",
//   "https://en.mchs.gov.ru/",
//   "https://fadm.gov.ru/",
//   "https://fadn.gov.ru/",
//   "https://favt.gov.ru/",
//   "https://fpi.gov.ru/",
//   "https://fsa.gov.ru/",
//   "https://fssp.gov.ru/",
//   "https://fsvps.gov.ru/",
//   "https://fsvts.gov.ru/",
//   "https://gfs.gov.ru/",
//   "https://gossluzhba.gov.ru/",
//   "https://ivanovskaya.roskazna.gov.ru/",
//   "https://kalmykia.fas.gov.ru/",
//   "https://kaluga.roskazna.gov.ru/",
//   "https://knd.ac.gov.ru/",
//   "https://knd.gov.ru/",
//   "https://lk.rpn.gov.ru/",
//   "https://mcx.gov.ru/",
//   "https://minenergo.gov.ru/",
//   "https://minfin.gov.ru/",
//   "https://minjust.gov.ru/",
//   "https://minobrnauki.gov.ru/",
//   "https://minobrnauki.sakha.gov.ru/",
//   "https://minpromtorg.gov.ru/",
//   "https://minstroyrf.gov.ru/",
//   "https://mintrans.gov.ru/",
//   "https://minzdrav.gov.ru/",
//   "https://morflot.gov.ru/",
//   "https://moscow.mchs.gov.ru/",
//   "https://moscow.roskazna.gov.ru/",
//   "https://moufk.roskazna.gov.ru/",
//   "https://nic.gov.ru/",
//   "https://obrnadzor.gov.ru/",
//   "https://ot.gov.ru/",
//   "https://pfr.gov.ru/",
//   "https://portal.audit.gov.ru/",
//   "https://proverki.gov.ru/",
//   "https://psi.mchs.gov.ru/",
//   "https://r14.fssp.gov.ru/",
//   "https://r16.fssp.gov.ru/",
//   "https://r19.fssp.gov.ru/",
//   "https://r21.fssp.gov.ru/",
//   "https://r22.fssp.gov.ru/",
//   "https://r23.fssp.gov.ru/",
//   "https://r27.fssp.gov.ru/",
//   "https://r35.fssp.gov.ru/",
//   "https://r38.fssp.gov.ru/",
//   "https://r43.fssp.gov.ru/",
//   "https://r45.fssp.gov.ru/",
//   "https://r47.fssp.gov.ru/",
//   "https://r53.fssp.gov.ru/",
//   "https://r57.fssp.gov.ru/",
//   "https://r58.fssp.gov.ru/",
//   "https://r61.fssp.gov.ru/",
//   "https://r63.fssp.gov.ru/",
//   "https://r66.fssp.gov.ru/",
//   "https://r69.fssp.gov.ru/",
//   "https://r70.fssp.gov.ru/",
//   "https://r77.fssp.gov.ru/",
//   "https://regulation.gov.ru/",
//   "https://rkn.gov.ru/",
//   "https://rlw.gov.ru/",
//   "https://rosavtodor.gov.ru/",
//   "https://rosguard.gov.ru/",
//   "https://rosim.gov.ru/",
//   "https://rospn.gov.ru/",
//   "https://rosreestr.gov.ru/",
//   "https://rosstat.gov.ru/",
//   "https://rs.gov.ru/",
//   "https://saratov.gov.ru/",
//   "https://sirius.gov.ru/",
//   "https://sozd.duma.gov.ru/",
//   "https://tomsk.gov.ru/",
//   "https://torgi.gov.ru/",
//   "https://tourism.gov.ru/",
//   "https://tyva.roskazna.gov.ru/",
//   "https://www.economy.gov.ru/",
//   "https://www.mchs.gov.ru/",
//   "https://www.mid.ru/",
//   "https://www.nalog.gov.ru/",
//   "https://www.sakha.gov.ru/",
//   "https://www.sberbank.ru/",
//   "https://www.vtb.ru/",
//   "https://zakupki.gov.ru/",
//   "https://zdrav.khv.gov.ru/",
//   "https://мвд.рф/",
//   "http://admin.gazprombank.ru",
// ];

const linksArray = [
  "https://yandex.by/",
  "https://vk.com/",
  "https://ok.ru/",
  "https://lenta.ru/",
  "https://ria.ru/",
  "https://ria.ru/lenta/",
  "https://www.rbc.ru/",
  "https://www.rt.com/",
  "http://kremlin.ru/",
  "http://en.kremlin.ru/",
  "https://smotrim.ru/",
  "https://tass.ru/",
  "https://tvzvezda.ru/",
  "https://vsoloviev.ru/",
  "https://www.1tv.ru/",
  "https://www.vesti.ru/",
  "https://online.sberbank.ru/",
  "https://sberbank.ru/",
  "https://zakupki.gov.ru/",
  "https://www.gosuslugi.ru/",
  "https://er.ru/",
  "https://www.rzd.ru/",
  "https://rzdlog.ru/",
  "https://vgtrk.ru/",
  "https://www.interfax.ru/",
  "https://www.mos.ru/uslugi/",
  "http://government.ru/",
  "https://mil.ru/",
  "https://www.nalog.gov.ru/",
  "https://customs.gov.ru/",
  "https://pfr.gov.ru/",
  "https://rkn.gov.ru/",
  "https://www.gazprombank.ru/",
  "https://www.vtb.ru/",
  "https://www.gazprom.ru/",
  "https://lukoil.ru",
  "https://magnit.ru/",
  "https://www.nornickel.com/",
  "https://www.surgutneftegas.ru/",
  "https://www.tatneft.ru/",
  "https://www.evraz.com/ru/",
  "https://nlmk.com/",
  "https://www.sibur.ru/",
  "https://www.severstal.com/",
  "https://www.metalloinvest.com/",
  "https://nangs.org/",
  "https://rmk-group.ru/ru/",
  "https://www.tmk-group.ru/",
  "https://ya.ru/",
  "https://www.polymetalinternational.com/ru/",
  "https://www.uralkali.com/ru/",
  "https://www.eurosib.ru/",
  "https://ugmk.ua/",
  "https://omk.ru/",
  "https://mail.rkn.gov.ru",
  "https://cloud.rkn.gov.r",
  "https://mvd.gov.r",
  "https://pwd.wto.economy.gov.ru/",
  "https://stroi.gov.ru",
  "https://proverki.gov.ru",
  "https://vk.com/",
  "https://www.gazprom.ru/",
  "https://lukoil.ru",
  "https://magnit.ru/",
  "https://www.nornickel.com/",
  "https://www.surgutneftegas.ru/",
  "https://www.tatneft.ru/",
  "https://www.evraz.com/ru/",
  "https://nlmk.com/",
  "https://www.sibur.ru/",
  "https://www.severstal.com/",
  "https://www.metalloinvest.com/",
  "https://nangs.org/",
  "https://rmk-group.ru/ru/",
  "https://www.tmk-group.ru/",
  "https://ya.ru/",
  "https://www.polymetalinternational.com/ru/",
  "https://www.uralkali.com/ru/",
  "https://www.eurosib.ru/",
  "https://omk.ru/",
  "https://www.sberbank.ru",
  "https://www.vtb.ru/",
  "https://www.gazprombank.ru/",
  "https://www.gosuslugi.ru/",
  "https://www.mos.ru/uslugi/",
  "http://kremlin.ru/",
  "http://government.ru/",
  "https://mil.ru/",
  "https://www.nalog.gov.ru/",
  "https://customs.gov.ru/",
  "https://pfr.gov.ru/",
  "https://rkn.gov.ru/",
  "http://lenta.ru/",
  "http://lenta.ru/",
  "http://lenta.ru/",
  "http://lenta.ru/",
  "https://www.tinkoff.ru/",
  "https://www.tinkoff.ru/",
  "https://www.tinkoff.ru/",
];

// module.exports = Array.from(new Set(linksArray));
module.exports = linksArray;
